builders:
  built_html:
    import: 'package:built_html/builder.dart'
    builder_factories: ['createBuilder']
    build_to: cache
    build_extensions:
      '.template.html': ['.html']
    auto_apply: dependents
    required_inputs: ['.js', '.css']
